---
# Home Assistant Glow
#
# Read your electricity meter by means of the pulse LED on your
# meter, useful if you do not have a serial port (P1).
# © Klaas Schoute
#
substitutions:
  device_name: home-assistant-glow
  friendly_name: Home Assistant Glow
  project_version: "4.0.0"
  device_description: "Measure your energy consumption with the pulse LED on your smart meter - Wemos D1 Mini"
  project_url: "github://klaasnicolaas/home-assistant-glow"

  # Define the GPIO pins
  pulse_pin: GPIO13
  status_led: GPIO5
  led_pin_red: GPIO2
  led_pin_green: GPIO4

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  name_add_mac_suffix: true
  project:
    name: "klaasnicolaas.home-assistant-glow"
    version: "${project_version}"

dashboard_import:
  package_import_url: '${project_url}/home-assistant-glow/d1_mini.yaml@main'

esp8266:
  board: d1_mini

packages:
  basis: '${project_url}/components/basis.yaml@main'
  status_led: '${project_url}/components/status_led.yaml@main'
  pulse_meter: '${project_url}/components/pulse_meter.yaml@main'

# Enable logging
logger:

# Allow OTA updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap:
    ssid: '${friendly_name}'

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# To have a "next url" for improv serial
web_server:
